# Secure configuration example for go-apt-mirror with TLS hardening
# Directory to store mirrored files and other control files.
dir = "/var/spool/go-apt-mirror"

# Maximum concurrent connections for an upstream server.
max_conns = 10

# Log configuration
[log]
level = "info"
format = "plain"

# TLS/HTTPS Security Configuration
[tls]
# Minimum TLS version (1.2 or 1.3) - defaults to 1.2 for compatibility
min_version = "1.2"

# Maximum TLS version (1.2 or 1.3) - leave empty for latest
max_version = "1.3"

# WARNING: Only set to true for testing - this disables certificate verification!
insecure_skip_verify = false

# Custom CA certificate file (optional)
# ca_cert_file = "/etc/ssl/certs/custom-ca.pem"

# Client certificate for mutual TLS authentication (optional)
# client_cert_file = "/etc/ssl/certs/client.pem"
# client_key_file = "/etc/ssl/private/client.key"

# Specify allowed cipher suites for extra security (optional)
# Leave empty to use Go's secure defaults
cipher_suites = [
    "TLS_AES_256_GCM_SHA384",           # TLS 1.3
    "TLS_CHACHA20_POLY1305_SHA256",     # TLS 1.3  
    "TLS_AES_128_GCM_SHA256",           # TLS 1.3
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",    # TLS 1.2
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",  # TLS 1.2
]

# Custom server name for SNI (optional)
# server_name = "mirror.example.com"

# Mirror configurations - use HTTPS URLs for security
[mirrors.ubuntu]
url = "https://archive.ubuntu.com/ubuntu"  # HTTPS instead of HTTP!
suites = ["jammy", "jammy-updates", "jammy-security"]
sections = ["main", "restricted", "universe", "multiverse"]
mirror_source = true
architectures = ["amd64", "arm64"]

[mirrors.ubuntu-security]
url = "https://security.ubuntu.com/ubuntu"  # HTTPS for security updates
suites = ["jammy-security"]
sections = ["main", "restricted", "universe", "multiverse"]
mirror_source = false
architectures = ["amd64", "arm64"]

[mirrors.debian]
url = "https://deb.debian.org/debian"  # HTTPS for Debian
suites = ["bookworm", "bookworm-updates"]
sections = ["main", "contrib", "non-free", "non-free-firmware"]
mirror_source = false
architectures = ["amd64", "arm64"]